version: '2'

services:

  octoprint:
    build: ./octoprint
    privileged: true
    restart: always
    volumes:
      - "/data/octoprint:/data"
    ports:
      - "5000"
    devices:
      - "/dev/ttyUSB0:/dev/ttyACM0"

  mjpg-streamer:
    build: ./mpeg
    privileged: true
    restart: always
    ports:
      - "5555:8080"
    devices:
      - "/dev/video0"
