version: '2'

services:

  octoprint:
    build: .
    privileged: true
    volumes:
      - ./data:/data
    ports:
      - "5000:5000"
      - "8080:8080"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/video0:/dev/video0"